package ob_item_service.controller;

import ob_item_service.model.ItemCategoryModel;
import ob_item_service.repository.ItemCategoryRepository;
import ob_item_service.repository.ItemRepository;
import org.springframework.beans.BeanUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

import java.net.URI;
import java.util.List;

@RestController
@RequestMapping("/api/vi")
public class ItemCategoryController {
    @Autowired
    private ItemCategoryRepository itemCategoryRepository;

    @Autowired
    private ItemRepository itemRepository;

    @GetMapping("/categories")
    public List<ItemCategoryModel> getAllItemCategory(){
        return itemCategoryRepository.findAll();
    }

    @GetMapping("/categories/{id}")
    public ItemCategoryModel getItemCategory(@PathVariable String id){
        return itemCategoryRepository.findById(id).orElseThrow(() -> new RuntimeException("Cannot Find Item Category By ID: "+id));
    }

    @PostMapping("/categories")
    public ResponseEntity<String> saveItemCategory(@RequestBody ItemCategoryModel categoryModel){
        ItemCategoryModel savedItem = itemCategoryRepository.insert(categoryModel);//it will create new document in table with autogenerated id, if id exist than exception in is thrown
        URI uri = ServletUriComponentsBuilder.fromCurrentRequest()
                .path("/{id}")
                .buildAndExpand(savedItem.getId())
                .toUri();
        //http://localhost:8081/api/v1/categories/611b7bcfef59e87f2e0e0d60
        return ResponseEntity.created(uri).build();
    }

    @PutMapping("/categories/{id}")
    public ResponseEntity<ItemCategoryModel> updateItemCategory(@PathVariable String id, @RequestBody ItemCategoryModel categoryModel){
        ItemCategoryModel itemCategoryModel = itemCategoryRepository.findById(id).orElseThrow(() -> new RuntimeException("Cannot Find Item Category By ID: "+id));
        BeanUtils.copyProperties(categoryModel,itemCategoryModel);//copy all data from categoryModel to itemCategoryModel
        itemCategoryModel = itemCategoryRepository.save(itemCategoryModel);//if request has id than it will update else it will insert new document with new autogenerated id
        return new ResponseEntity<>(itemCategoryModel, HttpStatus.OK);
    }

    @DeleteMapping("/categories/{id}")
    public ResponseEntity<String> deleteItemCategory(@PathVariable String id){
        //List<ItemModel> itemModels = itemRepository.findAllByCategoryId(id);
        itemRepository.deleteAllByCategoryId(id);
        itemCategoryRepository.deleteById(id);
        return new ResponseEntity<>(id, HttpStatus.OK);
    }

}
